name: Publish To NPM
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
  
    runs-on: ubuntu-latest

    name: 'publish npm'

    environment: npm

    steps:
      - uses: actions/checkout@v2 
        with:
          persist-credentials: false

      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/

      - name: publish 
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISHTONPM}} 
        run: npm publish
